version: "3"
services: 
  mqtt:
    container-name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - /home/administrador/mosquitto/config:/mosquitto/config
      - /home/administrador/mosquitto/data:/mosquitto/data
      - /home/administrador/mosquito/log:/mosquito/log
    ports:
      - 1883:1883
      - 9001:9001
      